version: '3'

# services
services:
  jira:
    container_name: 'customized-atlassian-jira'
    restart: always
    image: customized-atlassian-jira
    volumes:
      - './jira:/var/atlassian/jira'

# networks
networks:
  default:
    external:
      name: c101
