version: '3'
services:
  nginx:
    image: nginx
    container_name: 'nginx'
    external_links:
      - nexus
      - gitlab
    networks:
      - c001
    ports:
      - '80:80'
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./log:/var/log/nginx
      - ./www:/var/www
    command: [nginx-debug, '-g', 'daemon off;']

networks:
  c001:
    external: true