version: '3'

# services
services:
  mysql:
    image: redis
    restart: always
    container_name: 'customized-redis'
    volumes:
      - './data:/data'
    ports:
      - '16379:6379'
# networks
networks:
  default:
    external:
      name: c001