server:
  port: 8888


#spring:
#  data:
#    elasticsearch:
#      cluster-name: docker-cluster
#      cluster-nodes: '192.168.0.31:9200'
#      properties:
#        xpack.security.user: elastic:elastic
#      repositories:
#        enabled: true
#  elasticsearch:
#    rest:

#      uris:

spring:
  elasticsearch:
    rest:
      uris: 'http://192.168.0.31:9200'
      username: elastic
      password: elastic
  application:
    name: example
# 日志
logging:
  level:
    root: info
    com.dokers.demo.example: debug
    org.springframework.data: debug
  file:
    path: logs
    name: ${spring.application.name}.log