version: '3'

# services
services:
  redis:
    image: redis
    restart: always
    container_name: 'my-redis'
    volumes:
      - './redis/data:/data'
    ports:
      - 16379:6379

  mongo:
    image: mongo
    restart: always
    container_name: 'my-mongo'
    volumes:
      - './mongo/data:/data/db'
    ports:
      - 17017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin

  mongo-express:
    links:
      - mongo
    image: mongo-express
    restart: always
    container_name: 'my-mongo-express'
    ports:
      - 7017:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin

  zookeeper:
    image: zookeeper
    restart: always
    container_name: 'my-zookeeper'
    ports:
      - 12181:2181