version: '3'

# services
services:
  redis:
    image: redis
    restart: always
    container_name: 'my-redis'
    volumes:
      - './redis/data:/data'
#      - './redis.conf:/usr/local/etc/redis/redis.conf'
    ports:
      - 16379:6379
#    command: redis-server /usr/local/etc/redis/redis.conf

  mongo:
    image: mongo
    restart: always
    container_name: 'my-mongo'
    volumes:
      - './mongo/data:/data/db'
#      - './mongo/mongod.conf:/etc/mongo/mongod.conf'
    ports:
      - 17017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin
#    command: mongo --config /etc/mongo/mongod.conf

  mongo-express:
    links:
      - mongo
    image: mongo-express
    restart: always
    container_name: 'my-mongo-express'
    ports:
      - 7017:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin

  zookeeper:
    image: zookeeper
    restart: always
    container_name: 'my-zookeeper'
#    volumes:
#      - './zookeeper/zoo.cfg:/conf/zoo.cfg'
    ports:
      - 12181:2181

# networks
networks:
  default:
    external:
      name: c001