version: '3'

# services
services:
  mysql:
    container_name: 'customized-atlassian-mysql'
    restart: always
    image: customized-atlassian-mysql
    volumes:
      - './mysql:/var/lib/mysql'

# networks
networks:
  default:
    external:
      name: c101