version: '3'

# services
services:
  confluence:
    container_name: 'customized-atlassian-confluence'
    restart: always
    image: customized-atlassian-confluence
    ports:
      - '8002:8090'
    volumes:
      - v:/var/atlassian/confluence

# networks
networks:
  default:
    external:
      name: customized-atlassian

# volumes
volumes:
  v:
    external:
      name: 'customized-atlassian-confluence'
