version: '3'

# services
services:
  confluence:
    container_name: 'customized-atlassian-confluence'
    restart: always
    image: customized-atlassian-confluence
    volumes:
      - './confluence:/var/atlassian/confluence'

# networks
networks:
  default:
    external:
      name: c101
